### ISSUE TITLE
[Feat] 메뉴 조회 WHERE절 추가

### ISSUE THREAD

**Issue by KimHoDong** [JPA-3team/teamProject#6]
# 기능 추가/수정 요청
WHERE 절을 이용하여 조건 추가
## 기능 설명
이곳에 추가하거나 수정하고 싶은 기능에 대한 구체적인 설명을 작성해주세요.
금액 이상의 목록을 보인다.
## 기대하는 효과
이 기능을 추가하거나 수정함으로써 얻고자 하는 효과나 결과를 설명해주세요.

## 구현 가능성
이 기능의 구현이 가능한지, 가능하다면 어떤 방식으로 접근할 것인지에 대한 아이디어가 있다면 공유해주세요.

## TO-DO
- [ ] MenuController 에 메뉴 조회 + WHERE절 추가 메소드 추가
- [ ] MenuService 에 비지니스 로직 추가
- [ ] MenuRepository 에 쿼리문 추가
